//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Ubicacion = new HashSet<Ubicacion>();
        }
    
        public decimal Compra_ID { get; set; }
        public System.DateTime Compra_Fecha { get; set; }
        public decimal Compra_Cantidad { get; set; }
        public string Compra_Forma_Pago { get; set; }
        public string Compra_Tipo_Doc_Cliente { get; set; }
        public decimal Compra_Num_Doc_Cliente { get; set; }
        public decimal Compra_Total { get; set; }
        public decimal Compra_Publicacion { get; set; }
        public bool Compra_Facturada { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Publicacion Publicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ubicacion> Ubicacion { get; set; }
    }
}
