//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premio_X_Cliente
    {
        public string Pre_Cli_Tipo_Doc { get; set; }
        public decimal Pre_Cli_Nro_Doc { get; set; }
        public int Pre_Premio_ID { get; set; }
        public int Pre_Cli_Canje_ID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Premio Premio { get; set; }
    }
}
