//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Premio()
        {
            this.Premio_X_Cliente = new HashSet<Premio_X_Cliente>();
        }
    
        public int Premio_ID { get; set; }
        public string Premio_Nombre { get; set; }
        public string Premio_Descripcion { get; set; }
        public Nullable<int> Premio_Puntos_Necesarios { get; set; }
        public string Premio_Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Premio_X_Cliente> Premio_X_Cliente { get; set; }
    }
}
