//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicacion()
        {
            this.Factura = new HashSet<Factura>();
            this.Ubicacion = new HashSet<Ubicacion>();
            this.Compra = new HashSet<Compra>();
        }
    
        public decimal Publicacion_ID { get; set; }
        public decimal Publicacion_Espectaculo { get; set; }
        public System.DateTime Publicacion_Fecha { get; set; }
        public Nullable<int> Publicacion_Localidades { get; set; }
        public Nullable<int> Publicacion_Grado { get; set; }
        public string Publicacion_Empresa { get; set; }
        public int Publicacion_Estado { get; set; }
        public System.DateTime Publicacion_Fecha_Espectaculo { get; set; }
    
        public virtual Espectaculo Espectaculo { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Grado_Publicacion Grado_Publicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ubicacion> Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
    }
}
