//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public decimal Ubicacion_Publicacion { get; set; }
        public string Ubicacion_Fila { get; set; }
        public decimal Ubicacion_Asiento { get; set; }
        public Nullable<bool> Ubicacion_Sin_numerar { get; set; }
        public decimal Ubicacion_Precio { get; set; }
        public string Ubicacion_Tipo { get; set; }
        public Nullable<decimal> Ubicacion_Compra { get; set; }
        public bool Ubicacion_Disponible { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        public virtual Compra Compra { get; set; }
    }
}
