//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public decimal Cli_Dni { get; set; }
        public string Cli_Apellido { get; set; }
        public string Cli_Nombre { get; set; }
        public Nullable<System.DateTime> Cli_Fecha_Nac { get; set; }
        public string Cli_Mail { get; set; }
        public string Cli_Dom_Calle { get; set; }
        public Nullable<decimal> Cli_Nro_Calle { get; set; }
        public Nullable<decimal> Cli_Piso { get; set; }
        public string Cli_Depto { get; set; }
        public string Cli_Cod_Postal { get; set; }
        public string Cli_CUIL { get; set; }
        public string Cli_Telefono { get; set; }
        public string Cli_Localidad { get; set; }
        public Nullable<System.DateTime> Cli_Fecha_Alta { get; set; }
        public string Cli_Tarjeta_Num { get; set; }
        public string Cli_Tarjeta_Tipo { get; set; }
        public string Cli_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
