//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public Compra()
        {
            this.Ubicacion = new HashSet<Ubicacion>();
        }
    
        public decimal Compra_ID { get; set; }
        public Nullable<System.DateTime> Compra_Fecha { get; set; }
        public Nullable<decimal> Compra_Cantidad { get; set; }
        public int Compra_Forma_Pago { get; set; }
        public decimal Compra_Cliente { get; set; }
    
        public virtual Puntos Puntos { get; set; }
        public virtual ICollection<Ubicacion> Ubicacion { get; set; }
    }
}
