//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espectaculo
    {
        public Espectaculo()
        {
            this.Publicacion = new HashSet<Publicacion>();
        }
    
        public decimal Espectaculo_Cod { get; set; }
        public string Espectaculo_Descripcion { get; set; }
        public Nullable<int> Espectaculo_Rubro { get; set; }
        public Nullable<System.DateTime> Espectaculo_Fecha { get; set; }
        public Nullable<System.DateTime> Espectaculo_Fecha_Venc { get; set; }
    
        public virtual Rubro Rubro { get; set; }
        public virtual ICollection<Publicacion> Publicacion { get; set; }
    }
}
