//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espec_Empresa
    {
        public string Espec_Empresa_Cuit { get; set; }
        public string Espec_Empresa_Razon_Social { get; set; }
        public Nullable<System.DateTime> Espec_Empresa_Fecha_Creacion { get; set; }
        public string Espec_Empresa_Mail { get; set; }
        public string Espec_Empresa_Dom_Calle { get; set; }
        public Nullable<decimal> Espec_Empresa_Nro_Calle { get; set; }
        public Nullable<decimal> Espec_Empresa_Piso { get; set; }
        public string Espec_Empresa_Depto { get; set; }
        public string Espec_Empresa_Cod_Postal { get; set; }
        public string Espec_Empresa_Telefono { get; set; }
        public string Espec_Empresa_Localidad { get; set; }
        public string Espec_Empresa_Ciudad { get; set; }
        public string Espec_Empresa_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
