//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espec_Empresa
    {
        public string Espec_Empresa_Cuit { get; set; }
        public string Espec_Empresa_Razon_Social { get; set; }
        public Nullable<System.DateTime> Espec_Empresa_Fecha_Creacion { get; set; }
        public string Espec_Empresa_Mail { get; set; }
        public string Espec_Empresa_Dom_Calle { get; set; }
        public Nullable<decimal> Espec_Empresa_Nro_Calle { get; set; }
        public Nullable<decimal> Espec_Empresa_Piso { get; set; }
        public string Espec_Empresa_Depto { get; set; }
        public string Espec_Empresa_Cod_Postal { get; set; }
        public string Espec_Empresa_Telefono { get; set; }
        public string Espec_Empresa_Localidad { get; set; }
        public string Espec_Empresa_Ciudad { get; set; }
        public string Espec_Empresa_Usuario { get; set; }
        public Nullable<bool> Espec_Empresa_Habilitado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
