//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Item_Factura = new HashSet<Item_Factura>();
        }
    
        public decimal Factura_Nro { get; set; }
        public Nullable<System.DateTime> Factura_Fecha { get; set; }
        public Nullable<decimal> Factura_Total { get; set; }
        public decimal Factura_Publicacion { get; set; }
    
        public virtual ICollection<Item_Factura> Item_Factura { get; set; }
    }
}
