//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionalidad
    {
        public Funcionalidad()
        {
            this.Rol = new HashSet<Rol>();
        }
    
        public int Func_ID { get; set; }
        public string Func_Descripcion { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
