//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Factura
    {
        public int Item_Factura_ID { get; set; }
        public decimal Item_Factura_Factura { get; set; }
        public Nullable<decimal> Item_Factura_Monto { get; set; }
        public Nullable<decimal> Item_Factura_Cantidad { get; set; }
        public string Item_Factura_Descripcion { get; set; }
        public Nullable<decimal> Item_Factura_Importe_Comision { get; set; }
        public decimal Item_Factura_Compra { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
