//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Factura
    {
        public int Item_Factura_ID { get; set; }
        public decimal Item_Factura_Factura { get; set; }
        public Nullable<decimal> Item_Factura_Monto { get; set; }
        public Nullable<decimal> Item_Factura_Cantidad { get; set; }
        public string Item_Factura_Descripcion { get; set; }
        public Nullable<decimal> Item_Factura_Importe_Comision { get; set; }
        public decimal Item_Factura_Compra { get; set; }
    }
}
