//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premio
    {
        public int Premio_ID { get; set; }
        public string Premio_Nombre { get; set; }
        public string Premio_Descripcion { get; set; }
        public Nullable<int> Premio_Puntos_Necesarios { get; set; }
        public Nullable<System.DateTime> Premio_Vencimiento { get; set; }
    }
}
