//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public decimal Publicacion_ID { get; set; }
        public decimal Publicacion_Espectaculo { get; set; }
        public Nullable<System.DateTime> Publicacion_Fecha { get; set; }
        public Nullable<int> Publicacion_Localidades { get; set; }
        public Nullable<int> Publicacion_Grado { get; set; }
        public string Publicacion_Empresa { get; set; }
        public int Publicacion_Estado { get; set; }
    
        public virtual Espectaculo Espectaculo { get; set; }
    }
}
