//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public decimal Publicacion_ID { get; set; }
        public decimal Publicacion_Espectaculo { get; set; }
        public Nullable<System.DateTime> Publicacion_Fecha { get; set; }
        public Nullable<int> Publicacion_Localidades { get; set; }
        public Nullable<int> Publicacion_Grado { get; set; }
        public string Publicacion_Empresa { get; set; }
        public int Publicacion_Estado { get; set; }
    
        public virtual Espectaculo Espectaculo { get; set; }
    }
}
