//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntos
    {
        public decimal Puntos_ID { get; set; }
        public string Puntos_Cantidad { get; set; }
        public Nullable<System.DateTime> Puntos_Vencimiento { get; set; }
        public decimal Puntos_Cliente { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
