//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntos
    {
        public decimal Puntos_ID { get; set; }
        public string Puntos_Cantidad { get; set; }
        public Nullable<System.DateTime> Puntos_Vencimiento { get; set; }
        public decimal Puntos_Cliente { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
