//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.Funcionalidad = new HashSet<Funcionalidad>();
        }
    
        public string Rol_ID { get; set; }
        public string Rol_Nombre { get; set; }
        public Nullable<bool> Rol_Habilitado { get; set; }
    
        public virtual ICollection<Funcionalidad> Funcionalidad { get; set; }
    }
}
