//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public Rubro()
        {
            this.Espectaculo = new HashSet<Espectaculo>();
        }
    
        public int Rubro_ID { get; set; }
        public string Rubro_Descripcion { get; set; }
    
        public virtual ICollection<Espectaculo> Espectaculo { get; set; }
    }
}
