//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubro
    {
        public Rubro()
        {
            this.Espectaculo = new HashSet<Espectaculo>();
        }
    
        public int Rubro_ID { get; set; }
        public string Rubro_Descripcion { get; set; }
    
        public virtual ICollection<Espectaculo> Espectaculo { get; set; }
    }
}
