//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Ubicacion
    {
        public decimal Tipo_Ubicacion_Codigo { get; set; }
        public string Tipo_Ubicacion_Descripcion { get; set; }
    }
}
