//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public decimal Ubicacion_Publicacion { get; set; }
        public string Ubicacion_Fila { get; set; }
        public decimal Ubicacion_Asiento { get; set; }
        public Nullable<bool> Ubicacion_Sin_numerar { get; set; }
        public Nullable<decimal> Ubicacion_Precio { get; set; }
        public decimal Ubicacion_Tipo { get; set; }
        public Nullable<decimal> Ubicacion_Compra { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
