//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Espec_Empresa = new HashSet<Espec_Empresa>();
        }
    
        public string Usuario_Username { get; set; }
        public byte[] Usuario_Password { get; set; }
        public Nullable<int> Usuario_Intentos_Fallidos { get; set; }
        public string Usuario_Rol { get; set; }
        public Nullable<bool> Usuario_Habilitado { get; set; }
        public Nullable<bool> Usuario_Autogenerado { get; set; }
        public int Usuario_Inicios { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Espec_Empresa> Espec_Empresa { get; set; }
    }
}
