//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Espec_Empresa = new HashSet<Espec_Empresa>();
        }
    
        public string Usuario_Username { get; set; }
        public byte[] Usuario_Password { get; set; }
        public Nullable<int> Usuario_Intentos_Fallidos { get; set; }
        public string Usuario_Rol { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Espec_Empresa> Espec_Empresa { get; set; }
    }
}
