//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalcoNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public decimal Factura_Nro { get; set; }
        public Nullable<System.DateTime> Factura_Fecha { get; set; }
        public Nullable<decimal> Factura_Total { get; set; }
        public decimal Factura_Publicacion { get; set; }
    }
}
